language: php
sudo: false

php:
  - 5.6
  - 7.0
  - 7.1

matrix:
  fast_finish: true

before_script:
  - composer self-update
  - composer install --prefer-dist --no-interaction
  - if [[ $TRAVIS_PHP_VERSION = '7.1' ]]; then PHPUNIT_FLAGS="--coverage-clover=coverage.xml"; else PHPUNIT_FLAGS=""; fi

script:
  - ./vendor/bin/phpunit $PHPUNIT_FLAGS

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - if [ -f coverage.xml ]; then php ocular.phar code-coverage:upload --format=php-clover ./coverage.xml; fi
  - if [ -f coverage.xml ]; then bash <(curl -s https://codecov.io/bash); fi